/**
 * Inventário de modais/dialogs em uso no CRM (frontend local).
 * Exclui: dropdowns, popover Filtrar, toasts, command palette, ui-proto, primitives.
 */

export type ModalGroupId =
  | "crm"
  | "confirm"
  | "inbox"
  | "pipeline"
  | "settings"
  | "email"
  | "automations"
  | "campaigns"
  | "system";

export type ModalKind = "live" | "confirm" | "pin" | "note";

export type ConfirmPreset = {
  title: string;
  description: string;
  confirmLabel?: string;
  destructive?: boolean;
};

export type ModalUnit = {
  id: string;
  group: ModalGroupId;
  title: string;
  file: string;
  kind: ModalKind;
  confirm?: ConfirmPreset;
  note?: string;
  href?: string;
};

export const GROUPS: { id: ModalGroupId; label: string }[] = [
  { id: "crm", label: "CRM criar / editar" },
  { id: "confirm", label: "Confirmação" },
  { id: "inbox", label: "Inbox" },
  { id: "pipeline", label: "Pipeline" },
  { id: "settings", label: "Configurações" },
  { id: "email", label: "E-mail e canais" },
  { id: "automations", label: "Automações e IA" },
  { id: "campaigns", label: "Campanhas e time" },
  { id: "system", label: "Sistema e detalhe" },
];

export const UNITS: ModalUnit[] = [
  // ── CRM criar / editar ──────────────────────────────────────────
  {
    id: "contact-new",
    group: "crm",
    title: "Novo contato",
    file: "app/(app)/contacts/client-page.tsx",
    kind: "live",
  },
  {
    id: "contact-edit-quick",
    group: "crm",
    title: "Editar contato (rápido)",
    file: "components/crm/contact-edit-dialog.tsx",
    kind: "live",
  },
  {
    id: "company-new",
    group: "crm",
    title: "Nova empresa",
    file: "app/(app)/companies/client-page.tsx",
    kind: "live",
  },
  {
    id: "company-edit",
    group: "crm",
    title: "Editar empresa",
    file: "app/(app)/companies/client-page.tsx",
    kind: "note",
    note: "Não isolável — precisa de empresa da lista.",
    href: "/companies",
  },
  {
    id: "deal-new",
    group: "crm",
    title: "Novo negócio",
    file: "features/pipeline-v2/extras/add-deal-dialog.tsx",
    kind: "live",
  },
  {
    id: "product-new",
    group: "crm",
    title: "Novo produto",
    file: "features/products-v2/product-dialog.tsx",
    kind: "live",
  },
  {
    id: "quota-new",
    group: "crm",
    title: "Nova cota",
    file: "features/quotas/quota-dialog.tsx",
    kind: "live",
  },
  {
    id: "category-new",
    group: "crm",
    title: "Nova categoria de desconto",
    file: "features/quotas/category-dialog.tsx",
    kind: "live",
  },
  {
    id: "org-unit",
    group: "crm",
    title: "Nova unidade",
    file: "features/org-units/org-units-page.tsx",
    kind: "live",
  },
  {
    id: "tag-new",
    group: "crm",
    title: "Nova tag",
    file: "app/(app)/settings/tags/client-page.tsx",
    kind: "live",
  },
  {
    id: "field-new",
    group: "crm",
    title: "Novo campo customizado",
    file: "app/(app)/settings/custom-fields/client-page.tsx",
    kind: "live",
  },
  {
    id: "department-new",
    group: "crm",
    title: "Novo departamento",
    file: "features/conversations-settings/components/DepartmentsTab.tsx",
    kind: "live",
  },
  {
    id: "department-edit",
    group: "crm",
    title: "Editar departamento",
    file: "features/conversations-settings/components/DepartmentsTab.tsx",
    kind: "note",
    note: "Não isolável — precisa de departamento da lista.",
    href: "/settings/conversations",
  },
  {
    id: "quick-reply",
    group: "crm",
    title: "Nova resposta rápida",
    file: "features/conversations-settings/components/QuickMessagesTab.tsx",
    kind: "live",
  },
  {
    id: "tabulation-new",
    group: "crm",
    title: "Nova tabulação",
    file: "app/(app)/settings/tabulations/client-page.tsx",
    kind: "live",
  },
  {
    id: "demand-item",
    group: "crm",
    title: "Nova solicitação",
    file: "app/(app)/demands/client-page.tsx",
    kind: "live",
  },
  {
    id: "demand-board",
    group: "crm",
    title: "Novo board",
    file: "app/(app)/demands/client-page.tsx",
    kind: "note",
    note: "Inline na página.",
    href: "/demands",
  },
  {
    id: "demand-stage",
    group: "crm",
    title: "Nova fase",
    file: "app/(app)/demands/client-page.tsx",
    kind: "note",
    note: "Inline na página.",
    href: "/demands",
  },
  {
    id: "job-new",
    group: "crm",
    title: "Nova vaga",
    file: "app/(app)/job-openings/client-page.tsx",
    kind: "live",
  },
  {
    id: "task-agenda",
    group: "crm",
    title: "Nova tarefa (agenda)",
    file: "components/crm/tasks-view.tsx",
    kind: "live",
  },
  {
    id: "user-edit",
    group: "crm",
    title: "Editar usuário",
    file: "app/(app)/settings/team/edit-user-dialog.tsx",
    kind: "live",
  },
  {
    id: "user-create",
    group: "crm",
    title: "Criar usuário",
    file: "app/(app)/settings/team/client-page.tsx",
    kind: "note",
    note: "Inline na página da equipe.",
    href: "/settings/team",
  },
  {
    id: "user-password",
    group: "crm",
    title: "Trocar senha",
    file: "app/(app)/settings/team/client-page.tsx",
    kind: "note",
    note: "Inline na página da equipe.",
    href: "/settings/team",
  },
  {
    id: "catalog-new",
    group: "crm",
    title: "Novo catálogo",
    file: "features/catalogs-v2/catalog-wizard.tsx",
    kind: "live",
  },
  {
    id: "catalog-edit",
    group: "crm",
    title: "Editar catálogo",
    file: "features/catalogs-v2/catalogs-page.tsx",
    kind: "note",
    note: "Não isolável — precisa de catálogo da lista.",
    href: "/settings/catalogs",
  },
  {
    id: "contact-import",
    group: "crm",
    title: "Importar contatos",
    file: "app/(app)/contacts/client-page.tsx",
    kind: "note",
    note: "Inline na lista de contatos.",
    href: "/contacts",
  },
  {
    id: "contact-dupes",
    group: "crm",
    title: "Localizar duplicadas",
    file: "app/(app)/contacts/client-page.tsx",
    kind: "note",
    note: "Consulta a API de duplicatas da org.",
    href: "/contacts",
  },

  // ── Confirmação ─────────────────────────────────────────────────
  {
    id: "confirm-generic",
    group: "confirm",
    title: "Confirmar (AlertDialog)",
    file: "components/ui/confirm-dialog.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir tag?",
      description: "Esta ação não pode ser desfeita. A tag será removida dos contatos vinculados.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-contact",
    group: "confirm",
    title: "Excluir contato",
    file: "app/(app)/contacts/client-page.tsx",
    kind: "live",
  },
  {
    id: "confirm-company",
    group: "confirm",
    title: "Excluir empresa",
    file: "app/(app)/companies/client-page.tsx",
    kind: "live",
  },
  {
    id: "confirm-campaign",
    group: "confirm",
    title: "Excluir campanha",
    file: "app/(app)/campaigns/client-page.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir campanha?",
      description: "Tem certeza que deseja excluir Black Friday 2025? Esta ação não pode ser desfeita.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-tag",
    group: "confirm",
    title: "Excluir tag",
    file: "app/(app)/settings/tags/client-page.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir tag?",
      description: "A tag Lead quente será removida. Esta ação não pode ser desfeita.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-product",
    group: "confirm",
    title: "Excluir produto",
    file: "features/products-v2/products-page.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir produto?",
      description: "O produto e as ofertas vinculadas serão removidos.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-user",
    group: "confirm",
    title: "Excluir usuário",
    file: "app/(app)/settings/team/client-page.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir usuário",
      description: "Esta ação remove o acesso de Ana Souza. Conversas e negócios permanecem.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-automation",
    group: "confirm",
    title: "Excluir automação",
    file: "features/legacy-v1/automations-editor.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir automação?",
      description: "O fluxo e o histórico de execuções desta automação serão removidos.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "confirm-kanban-move",
    group: "confirm",
    title: "Mover negócio (kanban)",
    file: "components/pipeline/kanban-board.tsx",
    kind: "note",
    note: "AlertDialog acoplado ao board — ver /pipeline.",
    href: "/pipeline",
  },
  {
    id: "confirm-kanban-delete",
    group: "confirm",
    title: "Excluir negócio (kanban)",
    file: "components/pipeline/kanban-board.tsx",
    kind: "note",
    note: "AlertDialog acoplado ao board — ver /pipeline.",
    href: "/pipeline",
  },
  {
    id: "confirm-bulk-deals",
    group: "confirm",
    title: "Excluir negócios (bulk)",
    file: "components/pipeline/bulk-actions-bar.tsx",
    kind: "confirm",
    confirm: {
      title: "Excluir negócios",
      description: "3 negócios serão excluídos. Esta ação não pode ser desfeita.",
      confirmLabel: "Excluir",
      destructive: true,
    },
  },
  {
    id: "resolve-inbox",
    group: "confirm",
    title: "Encerrar conversa",
    file: "features/inbox-v2/extras/skip-automations-option.tsx",
    kind: "live",
  },

  // ── Inbox ───────────────────────────────────────────────────────
  {
    id: "tabulation",
    group: "inbox",
    title: "Tabulação",
    file: "features/inbox-v2/extras/tabulation-dialog.tsx",
    kind: "live",
  },
  {
    id: "channel-pick",
    group: "inbox",
    title: "Escolher canal de envio",
    file: "features/inbox-v2/extras/channel-pick-modal.tsx",
    kind: "live",
  },
  {
    id: "pin-duration",
    group: "inbox",
    title: "Duração do pin",
    file: "components/crm/pin-duration-dialog.tsx",
    kind: "pin",
  },
  {
    id: "task-inbox",
    group: "inbox",
    title: "Nova tarefa (inbox)",
    file: "features/inbox-v2/extras/task-dialog.tsx",
    kind: "live",
  },
  {
    id: "schedule-msg",
    group: "inbox",
    title: "Agendar mensagem",
    file: "features/inbox-v2/extras/schedule-dialog.tsx",
    kind: "live",
  },
  {
    id: "internal-tpl",
    group: "inbox",
    title: "Modelos internos",
    file: "features/inbox-v2/extras/internal-template-picker-modal.tsx",
    kind: "live",
  },
  {
    id: "agent-auto",
    group: "inbox",
    title: "Disparar automação",
    file: "features/inbox-v2/extras/agent-automation-picker-modal.tsx",
    kind: "live",
  },
  {
    id: "wa-tpl",
    group: "inbox",
    title: "Templates do WhatsApp",
    file: "features/inbox-v2/extras/template-picker-popover.tsx",
    kind: "live",
  },
  {
    id: "call-perm",
    group: "inbox",
    title: "Permissão de chamada",
    file: "components/inbox/call-permission-template-dialog.tsx",
    kind: "live",
  },
  {
    id: "favorites",
    group: "inbox",
    title: "Mensagens favoritas",
    file: "components/crm/favorites-panel.tsx",
    kind: "live",
  },
  {
    id: "forward-msg",
    group: "inbox",
    title: "Encaminhar mensagem",
    file: "components/inbox/chat-window.tsx",
    kind: "note",
    note: "Não isolável — acoplado ao ChatWindow.",
    href: "/inbox",
  },
  {
    id: "signature",
    group: "inbox",
    title: "Assinatura do agente",
    file: "components/inbox/chat-window.tsx",
    kind: "note",
    note: "Não isolável — acoplado ao ChatWindow.",
    href: "/inbox",
  },
  {
    id: "team-compose",
    group: "inbox",
    title: "Nova conversa (team chat)",
    file: "features/team-chat/compose-dialogs.tsx",
    kind: "live",
  },
  {
    id: "team-members",
    group: "inbox",
    title: "Adicionar membros (canal)",
    file: "features/team-chat/compose-dialogs.tsx",
    kind: "live",
  },

  // ── Pipeline ────────────────────────────────────────────────────
  {
    id: "loss-reason",
    group: "pipeline",
    title: "Motivo de perda",
    file: "components/pipeline/loss-reason-dialog.tsx",
    kind: "live",
  },
  {
    id: "bulk-edit",
    group: "pipeline",
    title: "Editar campos em massa",
    file: "components/pipeline/bulk-edit-fields-dialog.tsx",
    kind: "live",
  },
  {
    id: "bulk-progress",
    group: "pipeline",
    title: "Progresso de operação em massa",
    file: "components/pipeline/bulk-operation-progress-dialog.tsx",
    kind: "note",
    note: "Não isolável — precisa de operationId ao vivo.",
    href: "/pipeline",
  },
  {
    id: "pipeline-channels",
    group: "pipeline",
    title: "Canais do funil",
    file: "features/pipeline-v2/extras/pipeline-channels-modal.tsx",
    kind: "live",
  },
  {
    id: "filter-3col",
    group: "pipeline",
    title: "Filtro do funil (3 colunas)",
    file: "components/pipeline/kanban-filters/v2/variant-modal-three-col.tsx",
    kind: "live",
  },
  {
    id: "filter-2col",
    group: "pipeline",
    title: "Filtro do funil (2 colunas)",
    file: "components/pipeline/kanban-filters/v2/variant-modal-two-col.tsx",
    kind: "live",
  },
  {
    id: "filter-sheet",
    group: "pipeline",
    title: "Filtros avançados (sheet)",
    file: "components/pipeline/kanban-filters/filter-panel.tsx",
    kind: "note",
    note: "Sheet legado — o canônico é o modal 3 colunas.",
    href: "/showcase/pipeline-filters",
  },
  {
    id: "add-automation",
    group: "pipeline",
    title: "Automação da etapa",
    file: "app/(app)/settings/pipeline/add-automation-drawer.tsx",
    kind: "live",
  },
  {
    id: "funnel-automations",
    group: "pipeline",
    title: "Automações do funil",
    file: "components/pipeline/funnel-automations.tsx",
    kind: "note",
    note: "Wizard acoplado às etapas do funil.",
    href: "/settings/pipeline",
  },
  {
    id: "pipeline-dupes",
    group: "pipeline",
    title: "Localizar duplicados (lista)",
    file: "app/(app)/pipeline/list/client-page.tsx",
    kind: "note",
    note: "Inline na lista de negócios.",
    href: "/pipeline/list",
  },
  {
    id: "pipeline-import",
    group: "pipeline",
    title: "Importar / exportar negócios",
    file: "app/(app)/pipeline/list/client-page.tsx",
    kind: "note",
    note: "Inline na lista de negócios.",
    href: "/pipeline/list",
  },
  {
    id: "list-columns",
    group: "pipeline",
    title: "Configuração da lista",
    file: "app/(app)/contacts/client-page.tsx",
    kind: "note",
    note: "Também em empresas e pipeline/list.",
    href: "/contacts",
  },
  {
    id: "saleshub-convos",
    group: "pipeline",
    title: "Conversas do contato",
    file: "components/pipeline/sales-hub-view.tsx",
    kind: "note",
    note: "Não isolável — precisa de contato do Sales Hub.",
    href: "/saleshub",
  },
  {
    id: "deal-history",
    group: "pipeline",
    title: "Histórico do negócio",
    file: "components/pipeline/deal-history-button.tsx",
    kind: "note",
    note: "Sheet acoplado a um dealId.",
    href: "/pipeline",
  },

  // ── Settings ────────────────────────────────────────────────────
  {
    id: "schedule-shell",
    group: "settings",
    title: "Horário (expediente)",
    file: "features/settings/schedules/schedule-shared.tsx",
    kind: "live",
  },
  {
    id: "widget-config",
    group: "settings",
    title: "Configurar widget",
    file: "app/(app)/widgets/_components/widget-config-drawer.tsx",
    kind: "live",
  },
  {
    id: "telephony",
    group: "settings",
    title: "Telefonia IP",
    file: "features/softphone/components/telefonia/telephony-modal.tsx",
    kind: "live",
  },
  {
    id: "distribution",
    group: "settings",
    title: "Distribuição automática",
    file: "app/(app)/widgets/distribution/client-page.tsx",
    kind: "note",
    note: "Também abre pelo widget Configurar (acima).",
    href: "/widgets/distribution",
  },
  {
    id: "api-tokens",
    group: "settings",
    title: "Criar chave de API",
    file: "features/legacy-v1/settings/api-tokens.tsx",
    kind: "note",
    note: "Inline em /settings/api-tokens.",
    href: "/settings/api-tokens",
  },
  {
    id: "wa-templates-meta",
    group: "settings",
    title: "Novo template Meta",
    file: "features/legacy-v1/settings/whatsapp-templates.tsx",
    kind: "note",
    note: "Wizard 2xl acoplado à lista de templates.",
    href: "/settings/templates",
  },
  {
    id: "wa-templates-preview",
    group: "settings",
    title: "Preview de template Meta",
    file: "features/legacy-v1/settings/whatsapp-templates.tsx",
    kind: "note",
    note: "Abre a partir de uma linha da lista.",
    href: "/settings/templates",
  },
  {
    id: "wa-templates-clone",
    group: "settings",
    title: "Clonar templates entre canais",
    file: "features/legacy-v1/settings/whatsapp-templates.tsx",
    kind: "note",
    note: "Abre a partir da lista de templates.",
    href: "/settings/templates",
  },
  {
    id: "message-models-new",
    group: "settings",
    title: "Novo modelo de mensagem",
    file: "features/legacy-v1/settings/message-models/index.tsx",
    kind: "note",
    note: "Inline na biblioteca de modelos.",
    href: "/settings/templates",
  },
  {
    id: "legacy-templates",
    group: "settings",
    title: "Novo template interno",
    file: "features/legacy-v1/settings/templates.tsx",
    kind: "note",
    note: "Inline em modelos internos.",
    href: "/settings/templates",
  },
  {
    id: "segments",
    group: "settings",
    title: "Novo segmento",
    file: "features/legacy-v1/campaigns-segments.tsx",
    kind: "note",
    note: "Inline em /campaigns/segments.",
    href: "/campaigns/segments",
  },

  // ── E-mail e canais ─────────────────────────────────────────────
  {
    id: "create-channel",
    group: "email",
    title: "Novo canal",
    file: "components/channels/create-channel-dialog.tsx",
    kind: "live",
  },
  {
    id: "channel-webhook",
    group: "email",
    title: "Webhook do canal",
    file: "components/channels/create-channel-dialog.tsx",
    kind: "note",
    note: "Aninhado no wizard Novo canal (passo webhook).",
    href: "/settings/channels",
  },
  {
    id: "channel-config",
    group: "email",
    title: "Configurar canal",
    file: "features/legacy-v1/settings/channels.tsx",
    kind: "note",
    note: "Não isolável — precisa de canal da lista.",
    href: "/settings/channels",
  },
  {
    id: "meta-webhook",
    group: "email",
    title: "Webhook Meta",
    file: "components/channels/meta-config-panel.tsx",
    kind: "note",
    note: "Painel de um canal Meta já criado.",
    href: "/settings/channels",
  },
  {
    id: "wa-qr",
    group: "email",
    title: "QR WhatsApp",
    file: "components/channels/whatsapp-qr-modal.tsx",
    kind: "note",
    note: "Não isolável — precisa de channelId e faz poll no QR real.",
    href: "/settings/channels",
  },
  {
    id: "connect-email",
    group: "email",
    title: "Conectar e-mail",
    file: "features/email-v2/components/connect-email-modal.tsx",
    kind: "live",
  },
  {
    id: "compose-email",
    group: "email",
    title: "Novo e-mail",
    file: "features/email-v2/components/compose-modal.tsx",
    kind: "live",
  },
  {
    id: "email-rules",
    group: "email",
    title: "Regras de e-mail",
    file: "features/email-v2/components/email-rules-modal.tsx",
    kind: "live",
  },
  {
    id: "email-sheet",
    group: "email",
    title: "Detalhe de e-mail",
    file: "features/email-v2/components/email-detail-sheet.tsx",
    kind: "live",
  },

  // ── Automações e IA ─────────────────────────────────────────────
  {
    id: "new-automation",
    group: "automations",
    title: "Nova automação",
    file: "features/automations-v2/new-automation-modal.tsx",
    kind: "live",
  },
  {
    id: "step-picker",
    group: "automations",
    title: "O que deseja automatizar?",
    file: "components/automations/step-picker-modal.tsx",
    kind: "live",
  },
  {
    id: "flow-step",
    group: "automations",
    title: "Passo do fluxo (canvas)",
    file: "components/flow/flow-step-picker-modal.tsx",
    kind: "live",
  },
  {
    id: "step-config",
    group: "automations",
    title: "Configurar passo",
    file: "components/automations/step-config-panel.tsx",
    kind: "note",
    note: "Acoplado ao nó selecionado no editor.",
    href: "/automations",
  },
  {
    id: "agent-wizard",
    group: "automations",
    title: "Novo agente IA",
    file: "components/ai-agents/agent-wizard.tsx",
    kind: "live",
  },
  {
    id: "agent-playground",
    group: "automations",
    title: "Playground do agente",
    file: "components/ai-agents/agent-playground.tsx",
    kind: "live",
  },
  {
    id: "agent-edit-legacy",
    group: "automations",
    title: "Editar agente (legado)",
    file: "features/legacy-v1/ai-agents.tsx",
    kind: "note",
    note: "Não isolável — precisa de agente da lista.",
    href: "/ai-agents",
  },
  {
    id: "cockpit-cases",
    group: "automations",
    title: "Casos do cockpit",
    file: "features/ai-agents/academic-cockpit/cases-dialog.tsx",
    kind: "live",
  },
  {
    id: "logs-modal",
    group: "automations",
    title: "Logs da automação",
    file: "components/flow/logs-modal.tsx",
    kind: "live",
  },
  {
    id: "session-inspect",
    group: "automations",
    title: "Inspeção da sessão",
    file: "components/flow/session-inspection-modal.tsx",
    kind: "live",
  },
  {
    id: "flow-sim",
    group: "automations",
    title: "Simular fluxo",
    file: "components/flow/flow-simulator.tsx",
    kind: "live",
  },
  {
    id: "wa-preview",
    group: "automations",
    title: "Preview WhatsApp",
    file: "components/flow/whatsapp-customer-preview.tsx",
    kind: "live",
  },
  {
    id: "editor-config",
    group: "automations",
    title: "Configuração (editor legado)",
    file: "features/legacy-v1/automations-editor.tsx",
    kind: "note",
    note: "Vários dialogs no editor (config, logs, nome).",
    href: "/automations",
  },

  // ── Campanhas e time ────────────────────────────────────────────
  {
    id: "campaign-detail",
    group: "campaigns",
    title: "Detalhe da campanha",
    file: "features/campaigns/campaign-detail-drawer.tsx",
    kind: "live",
  },
  {
    id: "campaign-pause",
    group: "campaigns",
    title: "Pausar campanha",
    file: "app/(app)/campaigns/client-page.tsx",
    kind: "note",
    note: "Não é modal — ação direta com toast.",
    href: "/campaigns",
  },

  // ── Sistema e detalhe ───────────────────────────────────────────
  {
    id: "avatar-crop",
    group: "system",
    title: "Recortar avatar",
    file: "components/profile/avatar-crop-dialog.tsx",
    kind: "live",
  },
  {
    id: "activity-detail",
    group: "system",
    title: "Detalhe da atividade",
    file: "components/crm/activities/activity-detail-dialog.tsx",
    kind: "live",
  },
  {
    id: "contact-panel",
    group: "system",
    title: "Painel do contato",
    file: "components/contacts/contact-panel.tsx",
    kind: "note",
    note: "Sheet acoplado a um contactId — ver /contacts.",
    href: "/contacts",
  },
  {
    id: "demand-drawer",
    group: "system",
    title: "Item de demanda",
    file: "features/demands/item-drawer.tsx",
    kind: "note",
    note: "Não isolável — precisa de itemId.",
    href: "/demands",
  },
  {
    id: "native-apk",
    group: "system",
    title: "Atualizar APK nativo",
    file: "components/layout/native-apk-update-dialog.tsx",
    kind: "note",
    note: "Só monta no WebView Capacitor com APK desatualizado.",
  },
  {
    id: "mobile-update",
    group: "system",
    title: "App desatualizado (mobile)",
    file: "components/layout/mobile-app-update-dialog.tsx",
    kind: "note",
    note: "Só monta em viewport mobile quando o build divergiu.",
  },
];

export const FOUND_COUNT = UNITS.length;
export const LIVE_COUNT = UNITS.filter((u) => u.kind !== "note").length;
export const NOTE_COUNT = UNITS.filter((u) => u.kind === "note").length;
